# Generated by Django 3.1.1 on 2020-09-23 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0002_auto_20200922_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='tenant1_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant1_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant2_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant2_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant3_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant3_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant4_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant4_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='evict_notices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.evict_notices'),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='leases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.leases'),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='oth_docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.oth_docs'),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='tenant_payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.tenant_payments'),
        ),
        migrations.AlterField(
            model_name='units',
            name='oth_unit_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.oth_unit_income'),
        ),
        migrations.AlterField(
            model_name='units',
            name='reg_unit_expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.reg_unit_expenses'),
        ),
        migrations.AlterField(
            model_name='units',
            name='tenants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.tenants'),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_expense_pmts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.unit_expense_pmts'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ovrhd_expense_pmts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.ovrhd_expense_pmts'),
        ),
        migrations.AlterField(
            model_name='users',
            name='reg_ovrhd_expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.reg_ovrhd_expenses'),
        ),
        migrations.AlterField(
            model_name='users',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.units'),
        ),
    ]
