# Generated by Django 3.1.1 on 2020-11-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0002_auto_20201119_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line1',
            field=models.CharField(default='123 fake st', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Olney', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Maryland', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.PositiveIntegerField(default='20832'),
            preserve_default=False,
        ),
    ]
