# Generated by Django 3.1.1 on 2020-11-16 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0003_auto_20200923_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_number', models.PositiveIntegerField()),
                ('tenant_first', models.CharField(max_length=40)),
                ('tenant_last', models.CharField(max_length=40)),
                ('tenant_ssn', models.PositiveIntegerField()),
                ('tenant_email', models.EmailField(max_length=254)),
                ('tenant_start', models.DateField(default=datetime.date.today)),
                ('tenant_end', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('tenants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=80)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.PositiveIntegerField()),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.unit')),
            ],
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='evict_notices',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='leases',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='oth_docs',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='tenant_payments',
        ),
        migrations.RemoveField(
            model_name='units',
            name='oth_unit_income',
        ),
        migrations.RemoveField(
            model_name='units',
            name='reg_unit_expenses',
        ),
        migrations.RemoveField(
            model_name='units',
            name='tenants',
        ),
        migrations.RemoveField(
            model_name='units',
            name='unit_expense_pmts',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ovrhd_expense_pmts',
        ),
        migrations.RemoveField(
            model_name='users',
            name='reg_ovrhd_expenses',
        ),
        migrations.RemoveField(
            model_name='users',
            name='units',
        ),
        migrations.RenameModel(
            old_name='Evict_Notices',
            new_name='Evict_Notice',
        ),
        migrations.RenameModel(
            old_name='Leases',
            new_name='Lease',
        ),
        migrations.RenameModel(
            old_name='Tenant_Payments',
            new_name='Tenant_Payment',
        ),
        migrations.DeleteModel(
            name='Oth_Docs',
        ),
        migrations.DeleteModel(
            name='Oth_Unit_Income',
        ),
        migrations.DeleteModel(
            name='Ovrhd_Expense_Pmts',
        ),
        migrations.DeleteModel(
            name='Reg_Ovrhd_Expenses',
        ),
        migrations.DeleteModel(
            name='Reg_Unit_Expenses',
        ),
        migrations.DeleteModel(
            name='Tenants',
        ),
        migrations.DeleteModel(
            name='Unit_Expense_Pmts',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='tenant',
            name='evict_notices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.evict_notice'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.lease'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord_app.tenant_payment'),
        ),
    ]
