# Generated by Django 3.1.1 on 2020-11-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0003_auto_20201119_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='evict_notices',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_payments',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='tenants',
        ),
        migrations.RemoveField(
            model_name='user',
            name='units',
        ),
        migrations.AddField(
            model_name='tenant',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landlord_app.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landlord_app.user'),
            preserve_default=False,
        ),
    ]
