# Generated by Django 3.1.1 on 2020-11-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0004_auto_20201116_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
