# Generated by Django 3.1.1 on 2020-11-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0004_auto_20201120_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='address_line2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
