# Generated by Django 3.1.1 on 2020-11-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0005_auto_20201120_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_line1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
