# Generated by Django 3.1.1 on 2020-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0006_auto_20201120_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_line1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.PositiveIntegerField(),
        ),
    ]
