# Generated by Django 3.1.1 on 2020-11-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_ssn',
        ),
    ]
