# Generated by Django 3.1.1 on 2020-11-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0007_remove_tenant_tenant_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='bedrooms',
        ),
    ]
