# Generated by Django 3.1.1 on 2020-11-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0008_auto_20201119_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
