# Generated by Django 3.1.1 on 2020-12-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0009_remove_unit_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='landlord_app.state'),
            preserve_default=False,
        ),
    ]
