# Generated by Django 3.1.1 on 2020-12-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0010_unit_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord_app.state'),
        ),
    ]
