# Generated by Django 3.1.1 on 2020-12-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0011_auto_20201202_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord_app.state'),
        ),
    ]
