# Generated by Django 3.1.1 on 2020-12-04 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0013_auto_20201203_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='Unit',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='tenant',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord_app.lease'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='electric_ind',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='garbage_ind',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='othfee_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='othfee_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='petfee_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='petfee_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='water_ind',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
