# Generated by Django 3.1.1 on 2020-12-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_app', '0015_auto_20201207_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='lease',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
